language: rust
rust:
  - stable 
  - nightly
os:
  - osx
  - linux
env:
  - FEATURES="" IOS_ARCHS=""
matrix:
  include:
    - os: osx
      rust: stable
      env: FEATURES="exception" IOS_ARCHS=""
    - os: osx
      osx_image: xcode7.2
      rust: nightly
      env: FEATURES="exception" IOS_ARCHS="i386 x86_64 armv7 armv7s aarch64"
sudo: false
install:
  - ./travis_install.sh
  - >
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      export FEATURES="gnustep $FEATURES";
      export LIBRARY_PATH=$HOME/libobjc2_staging/lib:$LIBRARY_PATH;
      export LD_LIBRARY_PATH=$HOME/libobjc2_staging/lib:$LD_LIBRARY_PATH;
    fi
script:
  - ./travis_test.sh
addons:
  apt:
    packages:
      - clang-3.7
      - cmake
