language: rust
rust:
  - stable 
  - beta
  - nightly
sudo: false
install:
  - >
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      export CC="clang";
      export CXX="clang++";
      . gnustep_install.sh;
      export FEATURES="--features gnustep";
    else
      export FEATURES="";
    fi
script:
  - cargo build $FEATURES
  - cargo test $FEATURES
  - cargo doc $FEATURES
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - clang-3.7
      - cmake
