sudo: false
language: rust
cache: cargo
os: osx

# Run on master and PRs
if: branch = master

script:
- cargo test --workspace --verbose
- # TODO: cargo test --workspace --verbose --all-features

jobs:
  include:
  - name: MacOS 10.11
    osx_image: xcode7.3

  - name: MacOS 10.13 (with 32bit)
    osx_image: xcode9.4
    rust: nightly
    # 32-bit targets only have tier 3 support
    install: rustup component add rust-src
    script:
    - cargo test --workspace --verbose
    - # TODO: cargo test --workspace --verbose --all-features
    - # objc2_exception doesn't work on 32bit?
      cargo test --workspace --exclude objc2_exception --verbose -Z build-std --target i686-apple-darwin
    - # TODO: cargo test --workspace --verbose --all-features -Z build-std --target i686-apple-darwin

  - name: MacOS 11.3
    osx_image: xcode12.5

  - name: iOS nightly
    osx_image: xcode7.3
    rust: nightly
    before_install: rustup component add rust-src
    # Install rust-test-ios
    install: curl -LO https://github.com/SSheldon/rust-test-ios/releases/download/0.1.1/rust-test-ios && chmod +x rust-test-ios
    before_script:
      # Enable -Z build-std, 32-bit targets only have tier 3 support
      - printf '[unstable]\nbuild-std = ["std"]\n' > $HOME/.cargo/config.toml
      # Remove workspace since `rust-test-ios` is not made for that
      - rm Cargo.toml
    # TODO: env: FEATURES="exception"
    script: cd objc2 && ../rust-test-ios
