language: rust
rust:
  - stable 
  - nightly
os:
  - osx
  - linux
env:
  - FEATURES=""
  - FEATURES="exception"
matrix:
  exclude:
    - os: linux
      env: FEATURES="exception"
sudo: false
install: >
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    export FEATURES="gnustep $FEATURES";
    export CC="clang";
    export CXX="clang++";
    . gnustep_install.sh;
  fi
script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"
addons:
  apt:
    packages:
      - clang-3.7
      - cmake
