[package]
name = "objc"
version = "0.1.2"
authors = ["Steven Sheldon"]

description = "Objective-C Runtime bindings and wrapper for Rust."
keywords = ["objective-c", "osx", "ios", "cocoa", "uikit"]
readme = "README.md"
repository = "http://github.com/SSheldon/rust-objc"
documentation = "http://ssheldon.github.io/rust-objc/objc/"
license = "MIT"

exclude = [".gitignore"]

[dependencies]
libc = "0.1"
malloc_buf = "0.0"

[dev-dependencies.objc_test_utils]
version = "0.0"
path = "test_utils"
