[package]
name = "objc-tests"
version = "0.0.0"
authors = ["Steven Sheldon"]

build = "build.rs"

[lib]
name = "objc_tests"
path = "lib.rs"
crate-type = ["staticlib"]

[dependencies.objc]
path = ".."
features = ["exception"]

[build-dependencies]
regex = "0.1"
walkdir = "0.1"
