[package]
name = "objc-tests"
version = "0.0.0"
authors = ["Steven Sheldon"]

build = "build.rs"

[lib]
name = "objc_tests"
path = "lib.rs"

[dependencies]
libc = "*"

[dependencies.objc]
path = ".."
