[package]
name = "block2"
# Remember to update html_root_url in lib.rs and README.md
version = "0.1.6"
authors = ["Steven Sheldon", "Mads Marquart <mads@marquart.dk>"]
edition = "2018"

description = "Apple's C language extension of blocks"
keywords = ["objective-c", "macos", "ios", "blocks"]
categories = [
    "api-bindings",
    "development-tools::ffi",
    "os::macos-apis",
]
readme = "README.md"
repository = "https://github.com/madsmtm/objc2"
documentation = "https://docs.rs/block2/"
license = "MIT"

exclude = [
    "tests-ios/**",
]

[dependencies]
objc2-encode = { path = "../objc2-encode" }
block-sys = { path = "../block-sys" }

[dev-dependencies]
objc2_test_utils = { path = "../objc2_test_utils" }
