[package]
name = "objc"
version = "0.0.1"
authors = ["Steven Sheldon"]

description = "Objective-C Runtime bindings and wrapper for Rust."
repository = "http://github.com/SSheldon/rust-objc"
documentation = "http://ssheldon.github.io/rust-objc/objc/"

[lib]
name = "objc"
path = "lib.rs"
doctest = false
