[package]
name = "objc2"
version = "0.3.0-alpha.3" # Remember to update html_root_url in lib.rs
authors = ["Steven Sheldon", "Mads Marquart <mads@marquart.dk>"]
edition = "2018"

description = "Objective-C runtime bindings and interface."
keywords = ["objective-c", "macos", "ios", "objc_msgSend"]
categories = [
    "api-bindings",
    "development-tools::ffi",
    "os::macos-apis",
]
readme = "README.md"
repository = "https://github.com/madsmtm/objc2"
documentation = "https://docs.rs/objc2/"
license = "MIT"

exclude = [
    "doc.sh",
    "tests-ios/**",
]

build = "build.rs"

[features]
# Enables `objc2::exception::throw` and `objc2::exception::catch`
exception = ["cc"]

# Wrap every `objc2::msg_send` call in a `@try/@catch` block
catch_all = ["exception"]
verify_message = []
unstable_autoreleasesafe = []

[dependencies]
malloc_buf = "1.0"
objc-sys = { path = "../objc-sys", version = "0.0.1" }
objc2-encode = { path = "../objc2-encode", version = "2.0.0-alpha.1" }

[build-dependencies]
cc = { version = "1", optional = true }
