name: Apple

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  # Faster compilation and error on warnings
  RUSTFLAGS: "-C debuginfo=0 -D warnings"
  RUSTDOCFLAGS: "-D warnings"
  CARGO_TERM_VERBOSE: true

jobs:
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

  test:
    name: Test
    strategy:
      matrix:
        platform:
          - { os: macos-10.15    }
          - { os: macos-11       }
          # - { target: x86_64-apple-ios,         os: macos-latest, }
          # - { target: aarch64-apple-ios,        os: macos-latest, }

    runs-on: ${{ matrix.platform.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Cache Rust
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/
          target/
        key: ${{ matrix.platform.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ matrix.platform.os }}-cargo-

    - name: Install different Rust toolchain
      # A default toolchain is already installed
      if: matrix.platform.target
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.platform.target }}
        profile: minimal
        override: true

    - name: Check documentation
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --no-deps --document-private-items

    - name: Test without features
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-fail-fast --no-default-features

    - name: Test with features
      uses: actions-rs/cargo@v1
      with:
        command: test
        # Not using --all-features because some features are nightly-only
        args: --no-fail-fast --features malloc,block,exception,catch_all,verify_message

  build_32_bit:
    name: Build 32-bit

    # 32-bit support was removed in 10.15, so we can't test the binary, only build it
    runs-on: macos-10.15

    env:
      CARGO_BUILD_TARGET: i686-apple-darwin

    steps:
    - uses: actions/checkout@v2

    - name: Install nightly Rust # required for -Zbuild-std
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        components: rust-src

    - name: Download macOS 10.13 SDK (supports 32-bit)
      run: |
        wget https://github.com/alexey-lysiuk/macos-sdk/releases/download/10.13/MacOSX10.13.tar.bz2
        tar -xyf MacOSX10.13.tar.bz2
        echo "SDKROOT=$(pwd)/MacOSX10.13.sdk" >> $GITHUB_ENV

    - name: Build without features
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -Zbuild-std --tests --no-default-features

    - name: Build with features
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -Zbuild-std --tests --features malloc,exception,catch_all,verify_message
