name: GNUStep

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  # Faster compilation and error on warnings
  RUSTFLAGS: "-C debuginfo=0 -D warnings"
  CC: clang
  CXX: clang++

jobs:
  test:
    name: Test
    # TODO: 32bit and gcc-multilib
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Rust
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/
          target/
        key: gnustep-cargo-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          gnustep-cargo-

    - name: Install Packages
      run: sudo apt-get install gobjc clang make libblocksruntime-dev

    - # Run before we install GNUStep as a "fail fast" mechanism
      name: Run checks
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --verbose --no-default-features

    - name: Install GNUStep libobjc2
      run: |
        wget https://github.com/gnustep/libobjc2/archive/refs/tags/v1.9.tar.gz
        tar -xzf v1.9.tar.gz
        mkdir -p libobjc2-1.9/build
        cd libobjc2-1.9/build
        cmake ../
        sudo make install

    - name: Install GNUStep make
      run: |
        wget https://github.com/gnustep/tools-make/archive/refs/tags/make-2_9_0.tar.gz
        tar -xzf make-2_9_0.tar.gz
        cd tools-make-make-2_9_0
        ./configure --with-library-combo=ng-gnu-gnu
        sudo make install

    - name: Install GNUStep-Base
      run: |
        wget https://github.com/gnustep/libs-base/archive/refs/tags/base-1_28_0.tar.gz
        tar -xzf base-1_28_0.tar.gz
        cd libs-base-base-1_28_0
        ./configure --disable-tls
        sudo make install

    - name: Setup environment
      run: |
        ls -al /usr/local/lib
        ls -al /usr/local/include
        echo "LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "CPATH=/usr/local/include:$CPATH" >> $GITHUB_ENV

    - name: Test GNUStep
      uses: actions-rs/cargo@v1
      with:
        command: test
        # Temporary fix
        args: --verbose --no-fail-fast --no-default-features --package objc2_sys --package objc2 --package objc2_encode --package objc2_exception --package objc2_foundation

    - name: Test GNUStep with features
      uses: actions-rs/cargo@v1
      with:
        command: test
        # Temporary fix
        args: --verbose --no-fail-fast --no-default-features --features exception,verify_message --package objc2_sys --package objc2 --package objc2_encode --package objc2_exception --package objc2_foundation
